# Generated by Django 4.1.3 on 2022-12-01 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_brend', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_stock', models.CharField(max_length=50)),
                ('start_stock', models.CharField(max_length=50)),
                ('finish_stock', models.CharField(max_length=50)),
                ('persent_stock', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=50)),
                ('catagory', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('brend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.brend')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.stock')),
            ],
        ),
    ]
